org: dzmitrykliapkouprotofire
app: sampleproject
service: sampleproject

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.9
  cfnRole: "arn:aws:iam::${param:accountId}:role/strict-serverless-cloudformation-role"

functions:
  rateHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 hour)
